name: Main

on: [push, pull_request]

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: rustfmt
      - uses: actions/checkout@v2
      - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: clippy
      - uses: actions/checkout@v2
      - run: cargo clippy --all-targets --all-features -- -D clippy::all

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - uses: actions/checkout@v2
      - run: cargo check --all

  test:
    needs: [codestyle, lint, compile]
    runs-on: ubuntu-latest

    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Install Tarpaulin
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: 0.13.3
          use-tool-cache: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: cargo test
      - name: Coverage
        run: cargo tarpaulin --all-features -o Lcov --output-dir ./coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-docs:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - uses: actions/checkout@v2
      - name: Generate Docs
        shell: bash
        run: |
          cargo doc --no-deps
          echo "<meta http-equiv=refresh content=0;url=`echo ${{ github.repository  }} | cut -d / -f 2 | tr '-' '_'`/index.html>" > target/doc/index.html
      - name: Publish
        uses: docker://peaceiris/gh-pages:v2.3.1
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/doc
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          emptyCommits: true

  publish-crate:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - uses: actions/checkout@v1
      - name: Publish
        shell: bash
        run: |
          cargo publish --token ${{ secrets.CRATES_TOKEN }} --manifest-path formation/Cargo.toml
          sleep 5
          cargo publish --token ${{ secrets.CRATES_TOKEN }} --manifest-path forma/Cargo.toml
